<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,0,'5paw6Ze75Lit5b+D');
$cfg_Cs[2]=array(0,1,0,'5Y+k6ZWH6KeG6aKR');
$cfg_Cs[3]=array(0,1,0,'6aG555uu5Yqo5oCB');
$cfg_Cs[4]=array(0,1,0,'5paH5YyW6YGX5Lqn');
$cfg_Cs[5]=array(0,2,0,'5Zu+54mH5qyj6LWP');
$cfg_Cs[6]=array(0,1,0,'54m55Yir5LiT6aKY');
$cfg_Cs[7]=array(0,1,0,'5Lq654mp6aOO6YeH');
$cfg_Cs[8]=array(0,1,0,'5Y+k6ZWH6aOO5L+X');
$cfg_Cs[9]=array(0,1,0,'5Y+k6ZWH5L+d5oqk');
$cfg_Cs[10]=array(0,1,0,'5Y+k6ZWH5Lqn5Lia');
$cfg_Cs[11]=array(0,1,0,'5pS/562W5rOV6KeE');
$cfg_Cs[12]=array(0,1,0,'5Y+k6ZWH5bGV5pKt');
$cfg_Cs[13]=array(0,1,0,'5Y+k6ZWH5bu6562R');
?>