<?php
$z[0]=Array("arclist","\n          <li>\n            <div>\n              <a href=\"[field:arcurl/]\" target=\"_blank\" ><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"\" width=\"80\" height=\"70\" /></a>\n            </div>\n            <div class=\"pictitle\">\n              <a href=\"[field:arcurl/]\" target=\"_blank\">[field:shorttitle/]</a>\n            </div>\n          </li>\n          ",310,756);
$z[0][4]['typeid']="8";
$z[0][4]['type']="image";
$z[0][4]['row']="6";
$z[0][4]['titlelen']="100";
$z[1]=Array("arclist","\n              <li>\n                <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\n              </li>\n            ",946,1150);
$z[1][4]['typeid']="8";
$z[1][4]['row']="8";
$z[1][4]['titlelen']="100";
$z[1][4]['limit']="0,8";
$z[2]=Array("arclist","\n              <li>\n                <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\n              </li>\n            ",1337,1541);
$z[2][4]['typeid']="8";
$z[2][4]['row']="8";
$z[2][4]['titlelen']="100";
$z[2][4]['limit']="8,8";
$z[3]=Array("myad","",1702,1731);
$z[3][4]['name']="index-ad3";

?>