<?php
$z[0]=Array("arclist","\n              <li>\n                <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\n              </li>\n            ",330,536);
$z[0][4]['typeid']="9";
$z[0][4]['row']="10";
$z[0][4]['titlelen']="100";
$z[0][4]['limit']="0,10";
$z[1]=Array("arclist","\n              <li>\n                <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\n              </li>\n            ",682,889);
$z[1][4]['typeid']="9";
$z[1][4]['row']="10";
$z[1][4]['titlelen']="100";
$z[1][4]['limit']="10,10";
$z[2]=Array("arclist","\n          <li>\n            <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\n          </li>\n        ",1253,1431);
$z[2][4]['typeid']="11";
$z[2][4]['row']="10";
$z[2][4]['titlelen']="100";
$z[3]=Array("myad","",1525,1554);
$z[3][4]['name']="index-ad4";

?>