<?php
$z[0]=Array("arclist","\n      <li>\n        <div>\n          <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" width=\"156\" height=\"120\" /></a>\n        </div>\n        <div>\n          <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\n        </div>\n      </li>\n    ",40,373);
$z[0][4]['type']="image";
$z[0][4]['row']="12";
$z[0][4]['titlelen']="24";

?>