<?php
$z[0]=Array("arclist","\n        <li>\n          <div>\n            <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"\" width=\"135\" height=\"90\" /></a>\n          </div>\n          <div class=\"scrollTitle\">\n            <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\n          </div>\n        </li>\n        ",111,514);
$z[0][4]['type']="image";
$z[0][4]['row']="16";
$z[0][4]['titlelen']="100";

?>