<?php
$z[0]=Array("arclist","\n              <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"\" width=\"194\" height=\"112\" /></a>\n            ",329,575);
$z[0][4]['typeid']="6";
$z[0][4]['type']="image";
$z[0][4]['row']="1";
$z[0][4]['titlelen']="100";
$z[0][4]['limit']="0,1";
$z[1]=Array("arclist","\n                <li>\n                  <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\n                </li>\n              ",673,885);
$z[1][4]['typeid']="6";
$z[1][4]['row']="5";
$z[1][4]['titlelen']="100";
$z[1][4]['limit']="0,5";
$z[2]=Array("arclist","\n              <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"\" width=\"194\" height=\"112\" /></a>\n            ",1046,1292);
$z[2][4]['typeid']="6";
$z[2][4]['type']="image";
$z[2][4]['row']="1";
$z[2][4]['titlelen']="100";
$z[2][4]['limit']="1,1";
$z[3]=Array("arclist","\n                <li>\n                  <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\n                </li>\n              ",1390,1602);
$z[3][4]['typeid']="6";
$z[3][4]['row']="5";
$z[3][4]['titlelen']="100";
$z[3][4]['limit']="5,5";
$z[4]=Array("arclist","\n              <li>\n                <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\n              </li>\n            ",1767,1974);
$z[4][4]['typeid']="6";
$z[4][4]['row']="10";
$z[4][4]['titlelen']="100";
$z[4][4]['limit']="10,10";
$z[5]=Array("arclist","\n          <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"\" width=\"60\" height=\"60\" /></a>\n        ",2321,2546);
$z[5][4]['typeid']="7";
$z[5][4]['type']="image";
$z[5][4]['row']="3";
$z[5][4]['titlelen']="100";
$z[6]=Array("arclist","\n            <li>[field:description/] [<a href=\"[field:arcurl/]\" target=\"_blank\">详细</a>]</li>\n          ",2610,2782);
$z[6][4]['typeid']="7";
$z[6][4]['row']="3";
$z[6][4]['titlelen']="100";

?>