<?php
$z[0]=Array("arclist","\n  			linkarr[[field:global.autoindex/]] = \"[field:arcurl/]\";\n  			picarr[[field:global.autoindex/]]  = \"[field:litpic/]\";\n  			textarr[[field:global.autoindex/]] = \"[field:title function='html2text(@me)'/]\";\n  			",417,707);
$z[0][4]['typeid']="2";
$z[0][4]['type']="image";
$z[0][4]['row']="6";
$z[0][4]['titlelen']="100";
$z[1]=Array("arclist","\n          <li>\n            <span>[field:pubdate function=\"GetDateMK(@me)\"/]</span>\n            <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\n          </li>\n        ",2057,2313);
$z[1][4]['typeid']="2";
$z[1][4]['row']="16";
$z[1][4]['titlelen']="100";
$z[1][4]['noflag']="h";
$z[2]=Array("myad","",2370,2399);
$z[2][4]['name']="index-ad1";
$z[3]=Array("myad","",2430,2459);
$z[3][4]['name']="index-ad2";

?>