<?php
$z[0]=Array("global","",233,261);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",273,292);
$z[1][4]['name']="title";
$z[2]=Array("global","",295,321);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",364,394);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",430,457);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("include","",725,763);
$z[5][4]['filename']="_header.htm";
$z[6]=Array("field","",839,868);
$z[6][4]['name']="position";
$z[7]=Array("productimagelist","\n            <li>\n    					<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"60\" height=\"50\" /></a>\n    					<div>\n    					  <a href=\"[field:arcurl/]\" class=\"title\">[field:title/]</a>\n    					</div>\n    				</li>\n          ",1170,1452);
$z[8]=Array("include","",1534,1571);
$z[8][4]['filename']="_sider.htm";
$z[9]=Array("include","",1616,1654);
$z[9][4]['filename']="_block7.htm";
$z[10]=Array("include","",1657,1695);
$z[10][4]['filename']="_block8.htm";
$z[11]=Array("include","",1698,1736);
$z[11][4]['filename']="_footer.htm";

?>