<div class="pic">
                <a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" title="[field:title/]" width="114" height="80" /></a>
              </div>
              <div class="view">
                <h3><a href="[field:arcurl/]" target="_blank">[field:shorttitle/]</a></h3>
                <div class="info">
                  [field:description/][<a href="[field:arcurl/]" target="_blank">详细</a>]
                </div>
              </div>